# Generated by Django 3.2 on 2023-04-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Необязательное поле.', verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Обязательное поле. Не более 254 символов. Перед @ допустимы буквы и цифры.', max_length=254, unique=True, verbose_name='Электронный адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Аутентифицированный пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', help_text='Доступные варианты: Аутентифицированный пользователь, Модератор, Администратор.', max_length=9, verbose_name='Роль пользователя'),
        ),
    ]
