# Generated by Django 3.2 on 2023-04-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=256, verbose_name='Название')),
                ('year', models.IntegerField(help_text='Год выпуска', verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, help_text='Описание', null=True, verbose_name='Описание')),
            ],
        ),
    ]
