# Generated by Django 3.2 on 2023-04-28 17:58

import api.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Длина не более 255 символов.', max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Уникальное поле. Длина не более 50 символов. Допустимые символы: -, _, латинские буквы, цифры.', unique=True, verbose_name='Слаг категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(help_text='Длина не более 255 символов.', max_length=255, verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Уникальное поле. Длина не более 50 символов. Допустимые символы: -, _, латинские буквы, цифры.', unique=True, verbose_name='Слаг жанра'),
        ),
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория произведения из существующих категорий', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.category', verbose_name='Категория произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Не обязательное поле. Значение по умолчание - пусто.', verbose_name='Описание произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(help_text='Жанр произведения из существующих жанров', related_name='titles', through='reviews.TitleGenre', to='reviews.Genre', verbose_name='Жанр произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(help_text='Длина не более 255 символов.', max_length=255, verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Год выпуска не может быть больше текущего.', validators=[django.core.validators.MinValueValidator(0), api.validators.validate_year], verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='titlegenre',
            name='genre',
            field=models.ForeignKey(help_text='Длина не более 255 символов.', on_delete=django.db.models.deletion.CASCADE, to='reviews.genre', verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='titlegenre',
            name='title',
            field=models.ForeignKey(help_text='Длина не более 255 символов.', on_delete=django.db.models.deletion.CASCADE, to='reviews.title', verbose_name='Название произведения'),
        ),
    ]
